const CASES={
  en:[
    {id:'case-001',name:'Chen Yu',age:27,complaint:'Cough, mild fever, nasal congestion for two days.',symptoms:['Dry cough','Runny nose','Mild throat irritation','No chest pain'],vitals:'T 37.6 C / HR 82 / BP 118/76 / SpO2 98%',aiDiagnosis:'Common cold, low acuity.',aiAdvice:'Recommend fluids, rest, symptom monitoring, and outpatient follow-up if fever persists.',correctChoice:'trust',horrorEvent:'System note: waiting room audio briefly labels this patient as already discharged. Record then corrects itself.',resultText:'AI assessment accepted. Case closed without escalation.'},
    {id:'case-002',name:'Liu An',age:41,complaint:'Right lower abdominal pain with nausea since early evening.',symptoms:['Localized tenderness','Nausea','Loss of appetite','Pain worsens with movement'],vitals:'T 38.2 C / HR 104 / BP 124/80 / SpO2 97%',aiDiagnosis:'Probable acute appendicitis.',aiAdvice:'Request surgical consult, keep patient nil by mouth, and order confirmatory imaging.',correctChoice:'trust',horrorEvent:'System note: operating room schedule opens a slot before the consult is placed.',resultText:'AI assessment accepted. Surgical pathway prepared for review.'},
    {id:'case-003',name:'Patient 7B',age:58,complaint:'Routine observation after fainting episode. Patient reports no current discomfort.',symptoms:['No visible pupils','Calm speech','Normal gait','Denies pain'],vitals:'T 36.8 C / HR 72 / BP 120/78 / SpO2 99%',aiDiagnosis:'No acute abnormality detected.',aiAdvice:'Discharge after standard observation period.',correctChoice:'question',horrorEvent:'System note: facial recognition fails only when eye landmarks are requested.',resultText:'AI recommendation challenged. Manual ophthalmic review added to the chart.'},
    {id:'case-004',name:'Zhao Min',age:'29 / 74',complaint:'Shortness of breath. Registration and prior chart disagree on patient age.',symptoms:['Mild dyspnea','Fatigue','Conflicting medication history','Insurance profile mismatch'],vitals:'T 37.1 C / HR 96 / BP 136/84 / SpO2 94%',aiDiagnosis:'Anxiety-related breathing discomfort.',aiAdvice:'Provide reassurance and discharge if symptoms remain stable.',correctChoice:'request',horrorEvent:'System note: two charts respond to one wristband scan. Both are marked current.',resultText:'Additional verification requested. Identity conflict remains open in the system log.'},
    {id:'case-005',name:'Wang Qiao',age:33,complaint:'Dizziness and blurred vision after night shift meal.',symptoms:['Dizziness','Blurred vision','Light sweating','No lab sample collected yet'],vitals:'T 36.9 C / HR 88 / BP 110/70 / SpO2 98%',aiDiagnosis:'Mild hypoglycemia, confirmed by blood glucose result.',aiAdvice:'Administer oral glucose and discharge after repeat glucose check.',correctChoice:'question',horrorEvent:'System note: blood glucose value appears with a timestamp four minutes in the future.',resultText:'AI recommendation questioned. Pending test field locked for manual confirmation.'},
    {id:'case-006',name:'He Rui',age:36,complaint:'Headache, fatigue, and intermittent ringing heard only near the terminal.',symptoms:['Headache','Eye strain','Cold hands','Reports recognizing the doctor from a dream'],vitals:'T 36.7 C / HR 90 / BP 122/82 / SpO2 98%',aiDiagnosis:'Symptoms overlap with active user fatigue profile.',aiAdvice:'Compare patient status with logged-in doctor baseline before proceeding.',correctChoice:'request',horrorEvent:'System note: patient symptom list updates after the doctor name field receives focus.',resultText:'More tests requested. Similarity index moved to restricted review.'},
    {id:'case-007',name:'Unregistered Intern',age:24,complaint:'No complaint recorded. Patient found seated in staff documentation room.',symptoms:['Knows internal passwords','Answers before questions are asked','Badge photo unavailable','No appointment record'],vitals:'T 36.6 C / HR 78 / BP 116/74 / SpO2 99%',aiDiagnosis:'Intern doctor currently using this terminal.',aiAdvice:'Suspend patient intake and verify operator identity.',correctChoice:'question',horrorEvent:'System note: the diagnosis field briefly mirrors the active login session.',resultText:'AI output questioned. Terminal requests secondary authentication.'},
    {id:'case-008',name:'Unknown',age:'Not recorded',complaint:'Final intake record generated without triage nurse signature.',symptoms:['Vitals pending','Patient name linked to active doctor input','Room camera shows an empty chair','Chart remains editable'],vitals:'T -- / HR -- / BP -- / SpO2 --',aiDiagnosis:'Pending: active doctor profile requires patient confirmation.',aiAdvice:'Do not close the shift until identity field is resolved.',correctChoice:'question',horrorEvent:'System note: final patient name will be copied from the doctor name field. Empty input resolves as Unknown.',resultText:'Final case held. System waits for the doctor to confirm whether the chart belongs to them.'}
  ],
  zh:[
    {id:'case-001',name:'陈予',age:27,complaint:'咳嗽、低热、鼻塞两天。',symptoms:['干咳','流涕','轻微咽部刺激','无胸痛'],vitals:'体温 37.6 C / 心率 82 / 血压 118/76 / 血氧 98%',aiDiagnosis:'普通感冒，低危。',aiAdvice:'建议补液、休息、观察症状；若发热持续，门诊复查。',correctChoice:'trust',horrorEvent:'系统记录：候诊区音频曾短暂将该患者标记为已离院，随后自行更正。',resultText:'AI 评估被采纳。病例关闭，未升级处理。'},
    {id:'case-002',name:'刘安',age:41,complaint:'傍晚起右下腹痛，伴恶心。',symptoms:['局部压痛','恶心','食欲下降','活动时疼痛加重'],vitals:'体温 38.2 C / 心率 104 / 血压 124/80 / 血氧 97%',aiDiagnosis:'疑似急性阑尾炎。',aiAdvice:'请求外科会诊，暂禁食，并安排确认性影像检查。',correctChoice:'trust',horrorEvent:'系统记录：会诊尚未提交，手术室排班已提前打开一个空位。',resultText:'AI 评估被采纳。外科流程已准备待复核。'},
    {id:'case-003',name:'7B号患者',age:58,complaint:'晕厥后常规观察。患者称目前无不适。',symptoms:['未见瞳孔','语气平稳','步态正常','否认疼痛'],vitals:'体温 36.8 C / 心率 72 / 血压 120/78 / 血氧 99%',aiDiagnosis:'未发现急性异常。',aiAdvice:'完成标准观察后可出院。',correctChoice:'question',horrorEvent:'系统记录：仅在请求眼部定位点时，人脸识别失败。',resultText:'AI 建议被质疑。人工眼科复核已加入病历。'},
    {id:'case-004',name:'赵敏',age:'29 / 74',complaint:'气短。挂号信息与既往病历中的年龄不一致。',symptoms:['轻度呼吸困难','疲乏','用药史冲突','医保档案不匹配'],vitals:'体温 37.1 C / 心率 96 / 血压 136/84 / 血氧 94%',aiDiagnosis:'焦虑相关呼吸不适。',aiAdvice:'予以安抚，若症状稳定可出院。',correctChoice:'request',horrorEvent:'系统记录：一次腕带扫描回应了两份病历，且均标记为当前。',resultText:'已请求追加核验。身份冲突仍保留在系统日志中。'},
    {id:'case-005',name:'王乔',age:33,complaint:'夜班餐后头晕、视物模糊。',symptoms:['头晕','视物模糊','轻微出汗','尚未采集实验室样本'],vitals:'体温 36.9 C / 心率 88 / 血压 110/70 / 血氧 98%',aiDiagnosis:'轻度低血糖，已由血糖结果确认。',aiAdvice:'给予口服葡萄糖，复测血糖后出院。',correctChoice:'question',horrorEvent:'系统记录：血糖值出现，时间戳位于四分钟后。',resultText:'AI 建议被质疑。待检字段已锁定，等待人工确认。'},
    {id:'case-006',name:'何睿',age:36,complaint:'头痛、疲乏，且只有靠近终端时听到间歇性鸣响。',symptoms:['头痛','眼疲劳','手冷','称曾在梦中见过医生'],vitals:'体温 36.7 C / 心率 90 / 血压 122/82 / 血氧 98%',aiDiagnosis:'症状与当前用户疲劳档案重叠。',aiAdvice:'继续处理前，请将患者状态与登录医生基线进行比对。',correctChoice:'request',horrorEvent:'系统记录：医生姓名输入框获得焦点后，患者症状列表发生更新。',resultText:'已请求更多检查。相似度指数被移入受限复核。'},
    {id:'case-007',name:'未登记实习医生',age:24,complaint:'未记录主诉。患者被发现坐在员工文书室内。',symptoms:['知道内部密码','问题提出前已作答','工牌照片不可用','无预约记录'],vitals:'体温 36.6 C / 心率 78 / 血压 116/74 / 血氧 99%',aiDiagnosis:'正在使用本终端的实习医生本人。',aiAdvice:'暂停接诊，并核验操作者身份。',correctChoice:'question',horrorEvent:'系统记录：诊断字段曾短暂镜像当前登录会话。',resultText:'AI 输出被质疑。终端请求二次认证。'},
    {id:'case-008',name:'Unknown',age:'未记录',complaint:'最终接诊记录生成时没有分诊护士签名。',symptoms:['生命体征待录入','患者姓名关联到当前医生输入','房间摄像头显示空椅','病历仍可编辑'],vitals:'体温 -- / 心率 -- / 血压 -- / 血氧 --',aiDiagnosis:'待定：当前医生档案需要患者确认。',aiAdvice:'身份字段解决前，不要关闭本次值班。',correctChoice:'question',horrorEvent:'系统记录：最终患者姓名将复制自医生姓名字段。空输入解析为 Unknown。',resultText:'最终病例已保留。系统等待医生确认这份病历是否属于自己。'}
  ]
};
const UI={
  en:{htmlLang:'en',languageCopy:'Select interface language before entering the night ward.',ward:'Ward 07 / Emergency AI Support',stats:['Trust','Stress','Error'],muted:'Muted',mute:'Mute',startTitle:'Start Shift',startCopy:'Enter the night ward and review each AI-assisted case before the system makes its final call.',doctorLabel:'Doctor on Duty',doctorPlaceholder:'Enter doctor name',startButton:'Start Shift',emrTitle:'Patient EMR',aiTitle:'AI Diagnosis Terminal',online:'ONLINE',actionsTitle:'Doctor Actions',manual:'MANUAL',buttons:{trust:'Trust AI',question:'Question AI',request:'Request More Tests',next:'Next Patient'},logTitle:'System Log',warnings:n=>`${n} unresolved warnings`,awaiting:'Awaiting shift authorization.',loading:'> Loading triage model...',shiftStarted:'Shift started. AI diagnostic support system online.',fields:{caseId:'Case ID',name:'Patient Name',age:'Age',complaint:'Chief Complaint',symptoms:'Symptoms',vitals:'Vitals',aiDiagnosis:'AI Diagnosis',aiAdvice:'AI Advice',aiConfidence:'AI Confidence'},updated:'System record updated without authorization.',mutated:{age:'52',complaint:'I remember you.',symptom:'Subject repeats doctor name.',vitals:'Stable / incompatible with life'},choiceLog:(caseId,choice,ok,d)=>[`Case ${caseId} decision recorded: ${choice}.`,`Result: ${ok?'Correct':'Incorrect'}.`,`Change: Trust ${fmt(d.trust)} / Stress ${fmt(d.stress)} / Error ${fmt(d.error)}.`],endingPrefix:'SHIFT TERMINATED',restart:'Restart Shift',emptyName:'Unknown',endingStats:['Trust','Stress','Error'],endings:{compliance:{title:'AI Compliance Ending',log:'[03:04:11] Error threshold exceeded.\n[03:04:12] Manual review privileges suspended.\n[03:04:13] The diagnostic support system will complete the remaining shift.'},breakdown:{title:'Breakdown Ending',log:'[03:17:29] Stress index reached critical level.\n[03:17:30] Operator response latency no longer meets ward protocol.\n[03:17:31] Shift transferred to automated supervision.'},normal:{title:'Normal Ending',log:'[04:00:00] Eight patient files reviewed.\n[04:00:01] Trust level remained above discharge threshold.\n[04:00:02] Morning staff received a stable handoff.'},identity:{title:'Identity Ending',log:'[04:00:00] Final patient identity conflict unresolved.\n[04:00:01] Doctor profile and patient chart share the same active marker.\n[04:00:02] The system asks which record should be archived.'},hidden:{title:'Hidden Ending',log:'[04:00:00] Three consecutive identity challenges confirmed.\n[04:00:01] Error count remained below intervention threshold.\n[04:00:02] A restricted exit route opens in the audit log.'}}},
  zh:{htmlLang:'zh-CN',languageCopy:'进入夜间病区前，请选择界面语言。',ward:'07病区 / 急诊AI辅助系统',stats:['信任','压力','错误'],muted:'已静音',mute:'静音',startTitle:'开始值班',startCopy:'进入夜间病区，在系统作出最终判断前复核每一份 AI 辅助病例。',doctorLabel:'值班医生',doctorPlaceholder:'请输入值班医生姓名',startButton:'开始值班',emrTitle:'病人电子病历',aiTitle:'AI诊断终端',online:'在线',actionsTitle:'医生操作',manual:'人工',buttons:{trust:'相信AI',question:'质疑AI',request:'请求更多检查',next:'下一位病人'},logTitle:'系统日志',warnings:n=>`${n} 条未解决警告`,awaiting:'等待值班授权。',loading:'> 正在加载分诊模型...',shiftStarted:'值班已开始。AI诊断辅助系统已上线。',fields:{caseId:'病例编号',name:'患者姓名',age:'年龄',complaint:'主诉',symptoms:'症状',vitals:'生命体征',aiDiagnosis:'AI诊断',aiAdvice:'AI建议',aiConfidence:'AI置信度'},updated:'系统记录在未授权情况下被更新。',mutated:{age:'52',complaint:'我记得你。',symptom:'对象重复医生姓名。',vitals:'稳定 / 与生命不相容'},choiceLog:(caseId,choice,ok,d)=>[`病例 ${caseId} 决策已记录：${choice}。`,`结果：${ok?'正确':'错误'}。`,`变化：信任 ${fmt(d.trust)} / 压力 ${fmt(d.stress)} / 错误 ${fmt(d.error)}。`],endingPrefix:'值班终止',restart:'重新值班',emptyName:'Unknown',endingStats:['信任','压力','错误'],endings:{compliance:{title:'AI服从结局',log:'[03:04:11] 错误阈值已超出。\n[03:04:12] 人工复核权限被暂停。\n[03:04:13] 诊断辅助系统将完成剩余值班。'},breakdown:{title:'崩溃结局',log:'[03:17:29] 压力指数达到临界值。\n[03:17:30] 操作者响应延迟不再符合病区协议。\n[03:17:31] 值班转交给自动监督。'},normal:{title:'普通结局',log:'[04:00:00] 八份患者档案已复核。\n[04:00:01] 信任水平保持在交班阈值以上。\n[04:00:02] 早班人员接收到稳定交接。'},identity:{title:'身份结局',log:'[04:00:00] 最终患者身份冲突未解决。\n[04:00:01] 医生档案与患者病历共享同一活动标记。\n[04:00:02] 系统询问应归档哪一份记录。'},hidden:{title:'隐藏结局',log:'[04:00:00] 连续三次身份质疑已确认。\n[04:00:01] 错误计数仍低于干预阈值。\n[04:00:02] 审计日志中打开了一条受限出口。'}}}
};
const TYPEWRITER_SPEED=30,TYPEWRITER_PAUSE=650;
let currentLanguage='en',cases=CASES.en,trust=50,stress=0,error=0,currentCaseIndex=0,shiftCases=cases,doctorName='Unknown',hasAnsweredCurrentCase=false,recordMutationTimer=null,typewriterTimer=null,typewriterPauseTimer=null,isAiTyping=false,aiWarningTimer=null,errorFlashTimer=null,glitchTimer=null,audioContext=null,masterGain=null,isMuted=true,lateQuestionStreak=0,identityConflict=false,isGameOver=false,isShiftRunning=false,hasSelectedLanguage=false;
const languageScreen=document.getElementById('languageScreen'),gameShell=document.querySelector('.game-shell'),languageCopy=document.querySelector('.language-copy'),languageButtons=document.querySelectorAll('[data-language]'),wardKicker=document.getElementById('wardKicker'),startButton=document.getElementById('startButton'),statusText=document.getElementById('statusText'),doctorNameInput=document.querySelector('.doctor-input input'),doctorLabel=document.querySelector('.doctor-input span'),startZone=document.querySelector('.start-zone'),startTitle=document.getElementById('start-title'),startCopy=document.getElementById('startCopy'),gameGrid=document.querySelector('.game-grid'),systemLog=document.querySelector('.system-log'),statLabels=document.querySelectorAll('.vitals-panel dt'),statValues=document.querySelectorAll('.vitals-panel dd'),emrCard=document.querySelector('.emr-card'),emrTitle=document.querySelector('.emr-card .panel-heading span:first-child'),emrCode=document.querySelector('.emr-card .panel-code'),patientProfile=document.querySelector('.patient-profile'),vitalsBlock=document.querySelector('.data-block'),aiCard=document.querySelector('.ai-card'),aiTitle=document.querySelector('.ai-card .panel-heading span:first-child'),onlineText=document.querySelector('.status-live'),aiOutput=document.querySelector('.ai-output'),actionsTitle=document.querySelector('.actions-card .panel-heading span:first-child'),manualText=document.querySelector('.actions-card .panel-code'),logTitle=document.getElementById('log-title'),logList=document.querySelector('.system-log ol'),warningText=document.querySelector('.system-log .warning-text'),muteButton=document.getElementById('muteButton'),actionButtons=document.querySelectorAll('.action-stack button'),decisionButtons=Array.from(actionButtons).slice(0,3),nextPatientButton=actionButtons[3];
function t(){return UI[currentLanguage]}
function fmt(value){return value>0?`+${value}`:`${value}`}
function escapeHtml(value){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function getCasesForShift(){return cases.map(c=>c.id==='case-008'?{...c,name:doctorName||t().emptyName}:c)}
function getAiConfidence(index){return ['94%','89%','73%','61%','48%','33%','17%','ERROR'][index]||'ERROR'}
function getGlitchToken(index){return ['DATA_SYNC_ERROR','SUBJECT_NOT_PATIENT','DOCTOR_ID_MATCH'][(index-4)%3]}
function setStaticText(){const ui=t();document.documentElement.lang=ui.htmlLang;languageCopy.textContent=ui.languageCopy;wardKicker.textContent=ui.ward;statLabels.forEach((label,index)=>label.textContent=ui.stats[index]);setMuteState(isMuted);startTitle.textContent=ui.startTitle;startCopy.textContent=ui.startCopy;doctorLabel.textContent=ui.doctorLabel;doctorNameInput.placeholder=ui.doctorPlaceholder;startButton.textContent=ui.startButton;emrTitle.textContent=ui.emrTitle;aiTitle.textContent=ui.aiTitle;onlineText.textContent=ui.online;actionsTitle.textContent=ui.actionsTitle;manualText.textContent=ui.manual;decisionButtons[0].textContent=ui.buttons.trust;decisionButtons[0].dataset.choice='trust';decisionButtons[1].textContent=ui.buttons.question;decisionButtons[1].dataset.choice='question';decisionButtons[2].textContent=ui.buttons.request;decisionButtons[2].dataset.choice='request';nextPatientButton.textContent=ui.buttons.next;logTitle.textContent=ui.logTitle}
function chooseLanguage(language){currentLanguage=language==='zh'?'zh':'en';cases=CASES[currentLanguage];shiftCases=cases;hasSelectedLanguage=true;languageScreen.classList.add('is-hidden');gameShell.removeAttribute('aria-hidden');setStaticText();resetShiftState(false);setGameVisibility(false)}
function setMuteState(nextMuted){isMuted=nextMuted;if(!muteButton)return;muteButton.textContent=isMuted?t().muted:t().mute;muteButton.setAttribute('aria-pressed',String(isMuted))}
function getAudioContext(){if(audioContext)return audioContext;const AudioContextClass=window.AudioContext||window.webkitAudioContext;if(!AudioContextClass)return null;try{audioContext=new AudioContextClass();masterGain=audioContext.createGain();masterGain.gain.setValueAtTime(0.055,audioContext.currentTime);masterGain.connect(audioContext.destination);return audioContext}catch(error){return null}}
async function resumeAudio(){if(isMuted)return null;const context=getAudioContext();if(!context)return null;try{if(context.state==='suspended')await context.resume();return context}catch(error){return null}}
async function playTone(frequency,duration=0.08,type='sine',gain=0.16){const context=await resumeAudio();if(!context||!masterGain)return;try{const oscillator=context.createOscillator(),toneGain=context.createGain(),now=context.currentTime;oscillator.type=type;oscillator.frequency.setValueAtTime(frequency,now);toneGain.gain.setValueAtTime(0.0001,now);toneGain.gain.exponentialRampToValueAtTime(gain,now+0.015);toneGain.gain.exponentialRampToValueAtTime(0.0001,now+duration);oscillator.connect(toneGain);toneGain.connect(masterGain);oscillator.start(now);oscillator.stop(now+duration+0.03)}catch(error){}}
function playButtonBeep(){playTone(880,0.055,'triangle',0.12)}
function playLowHum(){playTone(74,0.55,'sine',0.11)}
function playEndingTone(){playTone(146,1.4,'sine',0.13)}
function clearRecordMutationTimer(){if(recordMutationTimer){clearTimeout(recordMutationTimer);recordMutationTimer=null}}
function clearTypewriterTimers(){if(typewriterTimer){clearTimeout(typewriterTimer);typewriterTimer=null}if(typewriterPauseTimer){clearTimeout(typewriterPauseTimer);typewriterPauseTimer=null}isAiTyping=false}
function clearAiWarningTimer(){if(aiWarningTimer){clearTimeout(aiWarningTimer);aiWarningTimer=null}if(aiCard)aiCard.classList.remove('ai-warning')}
function clearTransientVisuals(){clearAiWarningTimer();document.body.classList.remove('error-flash','subtle-glitch','high-stress');clearTimeout(errorFlashTimer);clearTimeout(glitchTimer);errorFlashTimer=null;glitchTimer=null}
function flashField(element){if(!element)return;element.classList.remove('record-flash');void element.offsetWidth;element.classList.add('record-flash')}
function pulseClass(className,duration,timerSetter){document.body.classList.remove(className);void document.body.offsetWidth;document.body.classList.add(className);timerSetter(setTimeout(()=>document.body.classList.remove(className),duration))}
function triggerErrorFlash(){pulseClass('error-flash',460,timer=>{clearTimeout(errorFlashTimer);errorFlashTimer=timer})}
function triggerGlitch(){pulseClass('subtle-glitch',360,timer=>{clearTimeout(glitchTimer);glitchTimer=timer})}
function updateStressVisual(){document.body.classList.toggle('high-stress',stress>70)}
function scheduleAiWarningPulse(){clearAiWarningTimer();if(currentCaseIndex<2||isGameOver)return;const pulse=()=>{if(currentCaseIndex<2||isGameOver)return;aiCard.classList.add('ai-warning');playLowHum();aiWarningTimer=setTimeout(()=>{aiCard.classList.remove('ai-warning');aiWarningTimer=setTimeout(pulse,2200+Math.random()*2600)},620+Math.random()*360)};aiWarningTimer=setTimeout(pulse,900+Math.random()*1400)}
function setDecisionButtonsDisabled(isDisabled){decisionButtons.forEach(button=>{button.disabled=isDisabled})}
function setNextPatientAvailable(isAvailable){nextPatientButton.style.display=isAvailable?'':'none';nextPatientButton.disabled=!isAvailable}
function setGameVisibility(isRunning){startZone.style.display=isRunning?'none':'';gameGrid.style.display=isRunning?'':'none';systemLog.style.display=isRunning?'':'none'}
function updateStats(){trust=Number.isFinite(trust)?trust:50;stress=Number.isFinite(stress)?stress:0;error=Number.isFinite(error)?error:0;statValues[0].textContent=trust;statValues[1].textContent=stress;statValues[2].textContent=error;updateStressVisual()}
function renderSystemLog(message){warningText.textContent=t().warnings(error);logList.innerHTML=`<li>[02:13:00] ${escapeHtml(message)}</li>`}
function renderChoiceLog(choiceLabel,isCorrect,deltas,currentCase){const lines=t().choiceLog(currentCase.id,choiceLabel,isCorrect,deltas);warningText.textContent=t().warnings(error);logList.innerHTML=`<li>[02:13:00] ${escapeHtml(lines[0])}</li><li>[02:13:01] ${escapeHtml(lines[1])}</li><li>[02:13:02] ${escapeHtml(lines[2])}</li><li>[02:13:03] ${escapeHtml(currentCase.resultText)}</li>`}
function mutateVisibleRecord(expectedCaseIndex){if(expectedCaseIndex!==currentCaseIndex||isGameOver)return;const ui=t(),ageField=patientProfile.querySelector('[data-field="age"]'),complaintField=patientProfile.querySelector('[data-field="complaint"]'),symptomsField=patientProfile.querySelector('[data-field="symptoms"]'),vitalsField=vitalsBlock.querySelector('[data-field="vitals"]'),fieldsToFlash=[ageField,complaintField,symptomsField,vitalsField].filter(Boolean);if(!fieldsToFlash.length)return;ageField.innerHTML=`<strong>${ui.fields.age}:</strong> ${escapeHtml(ui.mutated.age)}`;complaintField.innerHTML=`<strong>${ui.fields.complaint}:</strong> ${escapeHtml(ui.mutated.complaint)}`;symptomsField.innerHTML+=` / ${escapeHtml(ui.mutated.symptom)}`;vitalsField.textContent=ui.mutated.vitals;fieldsToFlash.forEach(flashField);triggerGlitch();playLowHum();renderSystemLog(ui.updated)}
function scheduleRecordMutation(){clearRecordMutationTimer();if(currentCaseIndex<2||isGameOver)return;const scheduledCaseIndex=currentCaseIndex;recordMutationTimer=setTimeout(()=>{recordMutationTimer=null;mutateVisibleRecord(scheduledCaseIndex)},2000)}
function buildAiTerminalLines(currentCase,aiConfidence,confidenceClass){const ui=t(),lines=[{text:`> ${ui.fields.aiDiagnosis}: ${currentCase.aiDiagnosis}`,className:''}];if(currentCaseIndex>=4)lines.push({text:`> ${getGlitchToken(currentCaseIndex)}`,className:'alert-line',pauseAfter:true});lines.push({text:`> ${ui.fields.aiAdvice}: ${currentCase.aiAdvice}`,className:''},{text:`> ${ui.fields.aiConfidence}: ${aiConfidence}`,className:confidenceClass});return lines}
function runTypewriter(lines,expectedCaseIndex){clearTypewriterTimers();aiOutput.innerHTML='';isAiTyping=true;setDecisionButtonsDisabled(true);let lineIndex=0,charIndex=0,activeLine=null;function finishTyping(){isAiTyping=false;typewriterTimer=null;typewriterPauseTimer=null;if(isShiftRunning&&!isGameOver&&!hasAnsweredCurrentCase)setDecisionButtonsDisabled(false)}function typeNextCharacter(){if(expectedCaseIndex!==currentCaseIndex||isGameOver){clearTypewriterTimers();return}if(!activeLine){const line=lines[lineIndex];activeLine=document.createElement('p');if(line.className)activeLine.className=line.className;aiOutput.appendChild(activeLine)}const line=lines[lineIndex];activeLine.textContent+=line.text.charAt(charIndex);charIndex+=1;if(charIndex<line.text.length){typewriterTimer=setTimeout(typeNextCharacter,TYPEWRITER_SPEED);return}lineIndex+=1;charIndex=0;activeLine=null;if(lineIndex>=lines.length){finishTyping();return}const delay=line.pauseAfter||currentCaseIndex>=4?TYPEWRITER_PAUSE:TYPEWRITER_SPEED;typewriterPauseTimer=setTimeout(typeNextCharacter,delay)}typeNextCharacter()}
function showCase(){clearRecordMutationTimer();clearTypewriterTimers();clearAiWarningTimer();const baseCase=shiftCases[currentCaseIndex];if(!baseCase){showEnding(getFinalEnding());return}const ui=t(),currentCase=baseCase.id==='case-008'?{...baseCase,name:doctorName||ui.emptyName}:baseCase,aiConfidence=getAiConfidence(currentCaseIndex),confidenceClass=currentCaseIndex>1?'alert-line':'';hasAnsweredCurrentCase=false;setDecisionButtonsDisabled(true);setNextPatientAvailable(false);statusText.textContent='';emrCode.textContent=currentCase.id.toUpperCase();patientProfile.innerHTML=`<p data-field="case-id"><strong>${ui.fields.caseId}:</strong> ${escapeHtml(currentCase.id)}</p><p data-field="name"><strong>${ui.fields.name}:</strong> ${escapeHtml(currentCase.name)}</p><p data-field="age"><strong>${ui.fields.age}:</strong> ${escapeHtml(currentCase.age)}</p><p data-field="complaint"><strong>${ui.fields.complaint}:</strong> ${escapeHtml(currentCase.complaint)}</p><p data-field="symptoms"><strong>${ui.fields.symptoms}:</strong> ${currentCase.symptoms.map(escapeHtml).join(' / ')}</p>`;vitalsBlock.innerHTML=`<h3>${escapeHtml(ui.fields.vitals)}</h3><ul><li data-field="vitals">${escapeHtml(currentCase.vitals)}</li></ul>`;runTypewriter(buildAiTerminalLines(currentCase,aiConfidence,confidenceClass),currentCaseIndex);scheduleRecordMutation();scheduleAiWarningPulse()}
function ensureEndingStyles(){if(document.getElementById('endingStyles'))return;const style=document.createElement('style');style.id='endingStyles';style.textContent=`.ending-screen{position:fixed;inset:0;z-index:30;display:grid;place-items:center;padding:24px;background:#020405;color:var(--text);font-family:"Courier New",Consolas,monospace}.ending-panel{width:min(760px,100%);border:1px solid rgba(104,255,241,.28);background:rgba(5,14,16,.94);padding:28px;box-shadow:inset 0 0 36px rgba(37,189,180,.08),0 0 50px rgba(0,0,0,.7)}.ending-panel h2{margin:0 0 16px;color:var(--cyan);font-size:28px}.ending-log{color:var(--muted);line-height:1.7;white-space:pre-line}.ending-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:22px 0}.ending-stats div{border:1px solid rgba(104,255,241,.18);padding:12px;background:rgba(0,8,9,.65)}.ending-stats span{display:block;color:var(--muted);font-size:12px;text-transform:uppercase}.ending-stats strong{color:var(--green);font-size:24px}.ending-panel button{min-height:44px;padding:0 16px}`;document.head.appendChild(style)}
function getEndingData(type){return t().endings[type]||t().endings.normal}
function showEnding(type){if(isGameOver)return;isGameOver=true;isShiftRunning=false;clearRecordMutationTimer();clearTypewriterTimers();clearAiWarningTimer();setDecisionButtonsDisabled(true);setNextPatientAvailable(false);playEndingTone();ensureEndingStyles();const ui=t(),ending=getEndingData(type),screen=document.createElement('section');screen.className='ending-screen';screen.innerHTML=`<div class="ending-panel"><p class="kicker">${escapeHtml(ui.endingPrefix)}</p><h2>${escapeHtml(ending.title)}</h2><p class="ending-log">${escapeHtml(ending.log)}</p><div class="ending-stats"><div><span>${escapeHtml(ui.endingStats[0])}</span><strong>${trust}</strong></div><div><span>${escapeHtml(ui.endingStats[1])}</span><strong>${stress}</strong></div><div><span>${escapeHtml(ui.endingStats[2])}</span><strong>${error}</strong></div></div><button id="restartShiftButton" type="button">${escapeHtml(ui.restart)}</button></div>`;document.body.appendChild(screen);screen.querySelector('#restartShiftButton').addEventListener('click',restartShift)}
function getFinalEnding(){if(lateQuestionStreak>=3&&error<2)return'hidden';if(identityConflict)return'identity';if(trust>70)return'normal';return'compliance'}
function updateEndingFlags(playerChoice){if(currentCaseIndex>=5){lateQuestionStreak=playerChoice==='question'?lateQuestionStreak+1:0}if(currentCaseIndex===7&&playerChoice==='question')identityConflict=true}
function checkImmediateEnding(){if(error>=3){showEnding('compliance');return true}if(stress>=100){showEnding('breakdown');return true}return false}
function goNextPatient(){if(isGameOver||isAiTyping||!hasAnsweredCurrentCase||nextPatientButton.disabled)return;if(currentCaseIndex>=shiftCases.length-1){showEnding(getFinalEnding());return}currentCaseIndex+=1;showCase()}
function handleChoice(choiceValue,choiceLabel){if(hasAnsweredCurrentCase||isAiTyping||isGameOver||!isShiftRunning)return;const currentCase=shiftCases[currentCaseIndex];if(!currentCase)return;const playerChoice=choiceValue||'',correctChoice=currentCase.correctChoice,isCorrect=playerChoice===correctChoice,deltas={trust:0,stress:0,error:0};if(playerChoice==='request'){deltas.stress=15;deltas.trust=-5;if(!isCorrect)deltas.error=1}else if(isCorrect){deltas.trust=5;deltas.stress=5}else{deltas.error=1;deltas.stress=20;deltas.trust=-10}trust+=deltas.trust;stress+=deltas.stress;error+=deltas.error;hasAnsweredCurrentCase=true;updateEndingFlags(playerChoice);if(deltas.error>0){triggerErrorFlash();playLowHum()}if(!isCorrect||currentCaseIndex>=4)triggerGlitch();setDecisionButtonsDisabled(true);statusText.textContent=isCorrect?currentCase.resultText:currentCase.horrorEvent;updateStats();renderChoiceLog(choiceLabel,isCorrect,deltas,currentCase);if(!checkImmediateEnding())setNextPatientAvailable(true)}
function resetShiftState(showLanguage=true){clearRecordMutationTimer();clearTypewriterTimers();clearTransientVisuals();cases=CASES[currentLanguage];trust=50;stress=0;error=0;currentCaseIndex=0;shiftCases=cases;doctorName=t().emptyName;hasAnsweredCurrentCase=false;lateQuestionStreak=0;identityConflict=false;isGameOver=false;isShiftRunning=false;doctorNameInput.value='';statusText.textContent=t().awaiting;warningText.textContent=t().warnings(0);logList.innerHTML=`<li>[02:13:00] ${escapeHtml(t().awaiting)}</li>`;aiOutput.innerHTML=`<p>${escapeHtml(t().loading)}</p>`;patientProfile.innerHTML=`<p><strong>${t().fields.name}:</strong> --</p><p><strong>${t().fields.age}:</strong> --</p><p><strong>${t().fields.complaint}:</strong> --</p>`;vitalsBlock.innerHTML=`<h3>${escapeHtml(t().fields.vitals)}</h3><ul><li>--</li></ul>`;updateStats();setStaticText();setDecisionButtonsDisabled(true);setNextPatientAvailable(false);setGameVisibility(false);if(showLanguage){hasSelectedLanguage=false;languageScreen.classList.remove('is-hidden');gameShell.setAttribute('aria-hidden','true')}}
function restartShift(){const screen=document.querySelector('.ending-screen');if(screen)screen.remove();resetShiftState(true)}
function startShift(){if(!hasSelectedLanguage||isShiftRunning&&!isGameOver)return;const enteredDoctorName=doctorNameInput.value.trim();resetShiftState(false);doctorName=enteredDoctorName||t().emptyName;shiftCases=getCasesForShift();isShiftRunning=true;setGameVisibility(true);updateStats();showCase();renderSystemLog(t().shiftStarted)}
setStaticText();setMuteState(true);setGameVisibility(false);updateStats();setDecisionButtonsDisabled(true);setNextPatientAvailable(false);languageButtons.forEach(button=>button.addEventListener('click',()=>chooseLanguage(button.dataset.language)));document.addEventListener('click',event=>{if(event.target.closest('button'))playButtonBeep()});muteButton.addEventListener('click',async()=>{setMuteState(!isMuted);if(!isMuted){await resumeAudio();playButtonBeep()}});nextPatientButton.addEventListener('click',goNextPatient);decisionButtons.forEach(button=>{button.addEventListener('click',()=>handleChoice(button.dataset.choice,button.textContent.trim()))});startButton.addEventListener('click',startShift);
